---
- name: Add VS Code GPG key
  ansible.builtin.get_url:
    url: https://packages.microsoft.com/keys/microsoft.asc
    dest: /etc/apt/trusted.gpg.d/microsoft.asc
  

- name: Add VS Code APT repository
  apt_repository:
    repo: deb [signed-by=/etc/apt/trusted.gpg.d/microsoft.asc] https://packages.microsoft.com/repos/vscode stable main

- name: Install VS Code
  apt: pkg=code state=latest
