---
- name: Installing basics
  apt: pkg=curl,tree,htop,ncdu,zsh state=latest

- name: Install DE
  apt: pkg=i3,lightdm,xautolock,pasystray,scrot,gimp,sxiv,sakura,imagemagick,pavucontrol,tango-icon-theme,ttf-mscorefonts-installer,lightdm-gtk-greeter-settings,pcmanfm,lxappearance,adwaita-icon-theme-full  state=latest

- name: Install Office Tools
  apt: pkg=libreoffice,hunspell-de-ch-frami,mythes-de-ch state=latest

