---

- name: Get Hasicorp GPG key
  ansible.builtin.get_url:
    url: https://apt.releases.hashicorp.com/gpg
    dest: /etc/apt/trusted.gpg.d/hashicorp.asc

- name: Add Hashicorp repository
  ansible.builtin.apt_repository:
    filename: hashicorp.list
    repo: deb [signed-by=/etc/apt/trusted.gpg.d/hashicorp.asc] https://apt.releases.hashicorp.com {{ansible_distribution_release}} main

- name: Iastall terraform
  apt: name=terraform
