---



# Container
- name: Started container with portforwarding
  lxd_container:
    name: "{{instance_name}}"
    state: started
    profiles: ["dev","gui", "work", "kvm"]
    wait_for_ipv4_addresses: true
    timeout: 600
    source:
      type: image
      mode: pull
      server: https://cloud-images.ubuntu.com/releases/
      protocol: simplestreams
      alias: jammy
    devices: "{{ lookup('template', './lxd-devices.j2')  }}"



