---



# Container
- name: Started container with portforwarding
  lxd_container:
    name: "{{instance_name}}"
    state: started
    profiles: ["dev","gui", "work"]
    wait_for_ipv4_addresses: true
    timeout: 600
    source:
      type: image
      mode: pull
      server: https://images.linuxcontainers.org
      protocol: simplestreams
      alias: ubuntu/jammy/cloud
    devices: "{{ lookup('template', './lxd-devices.j2')  }}"



