---
- name: Download IDEA archive
  get_url:
    url: https://download.jetbrains.com/idea/ideaIC-2020.2.1.tar.gz?_ga=2.60890412.1655821718.1599651781-298603070.1599651781
    dest: /tmp/idea.tar.gz

- name: Create dir
  file:
    path: "{{idea_dir}}"
    state: directory
  register: idea_directory

- name: Unarchive Terraform archive
  unarchive:
    src: /tmp/idea.tar.gz
    dest: "{{idea_dir}}"
    copy: no
  when: idea_directory is changed

- name: find folders from location
  find:
    paths: "{{idea_dir}}"
    file_type: directory
    patterns: "idea-IC-*"
    recurse: no
    use_regex: yes
  register: idea_dirs_to_link

- debug: var=idea_dirs_to_link

- name: Adding terraform command to user path
  file:
    src: "{{idea_dirs_to_link.files[0].path}}/bin/idea.sh"
    dest: "/home/{{idea_user}}/.local/bin/idea-ic"
    state: link

- name: Make terraform_user terraform directory owner
  file:
    path: "/home/ubuntu/.local"
    state: directory
    owner: "{{idea_user}}"
    group: "{{idea_user}}"
    recurse: yes
