---
- name: Download IDEA archive
  get_url:
    url: https://download.jetbrains.com/idea/ideaIC-2020.2.1.tar.gz?_ga=2.60890412.1655821718.1599651781-298603070.1599651781
    dest: /tmp/idea.tar.gz

- name: Create dir
  file:
    path: "{{idea_dir}}"
    state: directory
  register: idea_directory

- name: Unarchive Terraform archive
  unarchive:
    src: /tmp/idea.tar.gz
    dest: "{{idea_dir}}"
    copy: no
  when: idea_directory is changed

- name: Make terraform_user terraform directory owner
  file:
    path: "{{idea_dir}}"
    state: directory
    owner: "{{idea_user}}"
    group: "{{idea_user}}"
    recurse: yes

- name: Adding terraform command to user path
  file:
    src: "{{idea_dir}}/idea"
    dest: "~/.local/bin/idea"
    state: link
