---

# Dotnet7 available in regular ubuntu feed
# https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu-2204
- name: Download SDK repos
  get_url:
    url: https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb
    dest: /tmp/packages-microsoft-prod.deb

- name: Install SDK repos
  apt: deb="/tmp/packages-microsoft-prod.deb"

- name: Update APT cache
  apt: update_cache=yes

- name: Install Dotnet SDK
  apt: pkg=dotnet-sdk-7.0,aspnetcore-runtime-7.0 state=latest
  register: dotnetsdk





