---

- name: Check terraform version
  shell: "terraform --version 2>&1 | grep {{terraform_version}}"
  failed_when: false
  changed_when: false
  register: terraform_versions_match

- name: Dwonalod terraform archive
  get_url:
    url: https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip
    dest: /tmp/terraform-{{terraform_version}}.zip

- name: Install unzip to unarchive terraform
  apt:
    name: unzip
    state: present

- name: Create dir
  file:
    path: "{{terraform_dir}}"
    state: directory

- name: Unarchive Terraform archive
  unarchive:
    src: /tmp/terraform-{{terraform_version}}.zip
    dest: "{{terraform_dir}}"
    copy: no
  when: terraform_versions_match.rc != 0 

- name: Make terraform_user terraform directory owner
  file:
    path: "{{terraform_dir}}"
    state: directory
    owner: "{{terraform_user}}"
    group: "{{terraform_user}}"
    recurse: yes

- name: Adding terraform command to user path
  file:
    src: "{{terraform_dir}}/terraform"
    dest: /usr/bin/terraform
    state: link
