---

- name: Find releases
  uri:
    url: https://api.github.com/repos/kubernetes-sigs/aws-iam-authenticator/releases/latest
    return_content: true
    body_format: json
  register: json_response

- name: Creates directory
  file:
    path: /opt/aws-iam-authenticator
    state: directory

- name: Download and install
  get_url:
    url:  " {{ json_response.json | to_json | from_json| json_query(\"assets[?ends_with(name,'linux_amd64')].browser_download_url | [0]\") }}"
    mode: 555
    dest: /opt/aws-iam-authenticator/aws-iam-authenticator

- name: Adding command to user path
  file:
    src: "/opt/aws-iam-authenticator/aws-iam-authenticator"
    dest: /usr/local/bin/aws-iam-authenticator
    state: link


