---

- name: Installing depenedencies
  apt: pkg=curl,git,build-essential,ripgrep,fd-find,xclip state=latest

- name: Delete existing nvim
  file:
    path: "/opt/nvim-linux-x86_64"
    state: absent

- name: Create nvim home
  ansible.builtin.file:
    path: /opt/nvim
    state: directory

- name: Download and Unpack nvim
  ansible.builtin.unarchive:
    src: https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.tar.gz
    dest: /opt/nvim
    remote_src: yes
    extra_opts: ['--strip-components=1', '--show-stored-names']

- name: Ensure local bin exists
  ansible.builtin.file:
    path: "~/.local/bin"
    state: directory
  become: no

- name: Create sym link
  ansible.builtin.file:
    src: /opt/nvim/bin/nvim
    dest: "~/.local/bin/nvim"
    state: link
  become: no

- name: Copy nvim config from host
  copy:
    src=~/.config/nvim
    dest=~/.config/
  when: config_from_host
  become: no

- name: Enable csharp plugins
  when: use_csharp
  block:
    - name: Add roslyn repo to mason LSP 
      copy:
        dest: "~/.config/nvim/lua/plugins/mason-roslyn-lsp.lua"
        content: |
          return {
            { 
              "mason-org/mason.nvim", 
              opt = {
                registries = {
                    "github:mason-org/mason-registry",
                    "github:Crashdummyy/mason-registry"
                }
              }
            }
          }
      become: no
    - name: Add roslyn plugin
      copy:
        dest: "~/.config/nvim/lua/plugins/seblyng-roslyn.lua"
        content: |
          return {
            "seblyng/roslyn.nvim",
            ft = "cs",
            ---@module 'roslyn.config'
            ---@type RoslynNvimConfig
            opts = {
                -- your configuration comes here; leave empty for default settings
                -- NOTE: You must configure `cmd` in `config.cmd` unless you have installed via mason
            }
          }
      become: no

