---
- name: Installing zsh and git
  apt: pkg=zsh,git state=latest
  register: installation

- name: Backing up existing ~/.zshrc
  shell: "if [ -f ~/.zshrc ]; then mv ~/.zshrc ~/.zshrc.org; fi"
  when: installation is success
  become: no

- name: Cloning oh-my-zsh
  git:
    repo=https://github.com/robbyrussell/oh-my-zsh
    dest=~/.oh-my-zsh
  when: installation is success
  register: cloning
  become: no

- name: Clone zsh-autosuggestings
  git:
    repo=https://github.com/zsh-users/zsh-autosuggestions.git
    dest=~/.oh-my-zsh/plugins/zsh-autosuggestions
  when: cloning is success
  become: no

- name: Clone zsh-syntax-highlight
  git:
    repo=https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest=~/.oh-my-zsh/plugins/zsh-syntax-highlighting
  when: cloning is success
  become: no

- name: Creating new ~/.zshrc
  copy:
    src=~/.zshrc
    dest=~/.zshrc
  when: cloning is success
  become: no

- name: Change user shell to zsh
  user: name=ubuntu shell=/usr/bin/zsh
  when: cloning is success

- name: Change local to en-US UTF8
  action: command update-locale LC_ALL=en_US.UTF-8
  become: yes
