---
- name: Node Cloud
  hosts: all
  become: yes
  gather_facts: True

  roles:
    - base
    - nvim
    - ohmyzsh
    - x11forward
    - docker
    - code
    - dotnetdev
    - azure
    - terraform


