---

# java
- hosts: localhost
  connection: local
  roles:
    - role: lxd_container
      vars:
        instance_name: "jakarta"
        forwarded_port: []

# node / ts
- hosts: localhost
  connection: local
  roles:
    - role: lxd_container
      vars:
        instance_name: "newfoundland"
        forwarded_port: []

# go
- hosts: localhost
  connection: local
  roles:
    - role: lxd_container
      vars:
        instance_name: "gozo"
        forwarded_port: []
  tags:
    - go

# python
- hosts: localhost
  connection: local
  roles:
    - role: lxd_container
      vars:
        instance_name: "papua"
        forwarded_port: [8000]
  tags:
    - python

# dotnet
- hosts: localhost
  connection: local
  roles:
    - role: lxd_container
      vars:
        instance_name: "donna"
        forwarded_port: ["7780","7776","3000","8080", "5000","443","7777","7778","7781", "7783", "8086", "8081", "8082", "8083", "1313"]
        external_container_storage: "/mnt/docker/donna"
  tags:
    - dotnet

# testing
- hosts: localhost
  connection: local
  roles:
    - role: lxd_container
      vars:
         instance_name: "kayak"
         forwarded_port: []
  tags:
    - testing


- hosts: localhost
  connection: local
  roles:
    - role: lxd_container
      vars:
        instance_name: "elba"
        instance_type: virtual-machine
        forwarded_port: []
        profiles: ["dev","vm"]
  tags:
    - edge

