---
- name: Add Docker GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/trusted.gpg.d/docker.asc

- name: Add Docker APT repository
  ansible.builtin.apt_repository:
    filename: docker.list
    repo: deb [signed-by=/etc/apt/trusted.gpg.d/docker.asc] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable

- name: Install Docker And Dependencies
  apt: pkg=apt-transport-https,ca-certificates,curl,software-properties-common,docker-ce,docker-compose-plugin state=latest

- name: Add user to docker group
  user:
    name: ubuntu
    groups: docker
    append: yes

