---
- name: Add VS Code GPG key
  apt_key: url=https://packages.microsoft.com/keys/microsoft.asc

- name: Add VS Code APT repository
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main

- name: Install VS Code
  apt: pkg=code,libasound2 state=latest
