---
- name: Install Lazygit
  shell: |
   LAZYGIT_VERSION=$(curl -s "https://api.github.com/repos/jesseduffield/lazygit/releases/latest" | \grep -Po '"tag_name": *"v\K[^"]*')
   curl -Lo /tmp/lazygit.tar.gz "https://github.com/jesseduffield/lazygit/releases/download/v${LAZYGIT_VERSION}/lazygit_${LAZYGIT_VERSION}_Linux_x86_64.tar.gz"
   cd /tmp
   tar xf lazygit.tar.gz lazygit
   install /tmp/lazygit -D -t /usr/local/bin/
  register: lazygit
  become: yes




