---

- name: Install DotNet SDK
  when: ansible_distribution_release == "jammy"
  block:
    # Dotnet7 available in regular ubuntu feed
    # https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu-2204
    - name: Download SDK repos
      get_url:
        url: https://packages.microsoft.com/config/ubuntu/{{ansible_distribution_version}}/packages-microsoft-prod.deb
        dest: /tmp/packages-microsoft-prod.deb

    - name: Install SDK repos
      apt: deb="/tmp/packages-microsoft-prod.deb"

    - name: Update APT cache
      apt: update_cache=yes

- name: Install Dotnet SDK
  apt: pkg=dotnet-sdk-8.0,aspnetcore-runtime-8.0 state=latest
  register: dotnetsdk





