---

# java
- hosts: localhost
  connection: local
  roles:
    - role: lxd_container
      vars:
        instance_name: "jakarta"

# node / ts
- hosts: localhost
  connection: local
  roles:
    - role: lxd_container
      vars:
        instance_name: "newfoundland"

# go
- hosts: localhost
  connection: local
  roles:
    - role: lxd_container
      vars:
        instance_name: "gozo"

# python
- hosts: localhost
  connection: local
  roles:
    - role: lxd_container
      vars:
        instance_name: "papua"
        forwarded_port: 8000

# dotnet
- hosts: localhost
  connection: local
  roles:
    - role: lxd_container
      vars:
        instance_name: "donna"
