--- 

- name: Devloper Workstation
  hosts: localhost
  connection: local
  gather_facts: True
  roles:
    - lxd_profiles
    - role: lxd_container
      vars:
        instance_name: jakarta
        
    - role: lxd_container
      vars:
        instance_name: newfoundland        

