
# Profile initate box with ssh key
- hosts: localhost
  connection: local
  tasks:
    - name: Create a profile
      lxd_profile:
        name: dev
        state: present
        config: {
           "user.vendor-data": "#cloud-config\nssh_authorized_keys:\n  - {{ lookup('file', '~/.ssh/id_rsa.pub') }}\npackages:\n  - ssh\n  - ansible" }
        description: Dev profile
        devices:
          eth0:
            name: eth0
            nictype: bridged
            type: nic
            parent: lxdbr0
          root:
            path: /
            pool: default
            type: disk

# An example for creating a Ubuntu container and install python
- hosts: localhost
  connection: local
  tasks:
    - name: Create a started container
      lxd_container:
        name: jakarta
        state: started
        source:
          type: image
          mode: pull
          server: https://images.linuxcontainers.org
          protocol: simplestreams # lxd, if you get a 404, try setting protocol: simplestreams
          alias: ubuntu/focal/cloud
        profiles: ["dev"]
        wait_for_ipv4_addresses: true
        timeout: 600


