---

# java
- hosts: localhost
  connection: local
  roles:
    - role: lxd_container
      vars:
        instance_name: "jakarta"
        forwarded_port: []

# node / ts
- hosts: localhost
  connection: local
  roles:
    - role: lxd_container
      vars:
        instance_name: "newfoundland"
        forwarded_port: []

# go
- hosts: localhost
  connection: local
  roles:
    - role: lxd_container
      vars:
        instance_name: "gozo"
        forwarded_port: []
  tags:
    - go

# python
- hosts: localhost
  connection: local
  roles:
    - role: lxd_container
      vars:
        instance_name: "papua"
        forwarded_port: [8000]
  tags:
    - python

# dotnet
- hosts: localhost
  connection: local
  roles:
    - role: lxd_container
      vars:
        instance_name: "donna"
        forwarded_port: ["7780","7776","1313", "8080", "5000", "3000","7777","7781","8086"]

  tags:
    - dotnet
