---
- name: Python-Env
  hosts: all
  become: yes
  gather_facts: False
  pre_tasks:
   - name: Disable Periodic APT daily update
     raw: echo 'APT::Periodic::Enable "0";' > /etc/apt/apt.conf.d/02periodic
   - name: Disable Daily APT Service
     raw: systemctl disable apt-daily.service apt-daily.timer apt-daily-upgrade.service apt-daily-upgrade.timer
   - name: Stop Daily APT Service
     raw: systemctl stop  apt-daily.service apt-daily-upgrade.service apt-daily.timer apt-daily-upgrade.timer
   - name: Install python for Ansible
     raw: apt-get -y update && apt-get install -y python-minimal
     changed_when: False
   - setup: # aka gather_facts

  roles:
    - base
    - vim
    - ohmyzsh

