

Vagrant.configure("2") do |config|
  config.vm.hostname = "phuket"
  config.vm.box = "rvanlaar/bionic64-lxc"
  config.vm.define "Phuket"
  config.vm.provider :lxc do |lxc|
    # Same effect as 'customize ["modifyvm", :id, "--memory", "1024"]' for VirtualBox
    lxc.customize 'cgroup.memory.limit_in_bytes', '1024M'
  end

  if Vagrant.has_plugin?("vagrant-proxyconf")
    config.proxy.http = "http://194.138.0.33:9400"
    config.proxy.https = "http://194.138.0.33:9400"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end

  #share work directory
  config.vm.synced_folder "~/work/", "/home/vagrant/work" 

  config.ssh.forward_agent = true
  config.ssh.forward_x11 = true

end
