

Vagrant.configure("2") do |config|
  config.vm.hostname = "keppel"
  config.vm.box = "rvanlaar/bionic64-lxc"
  config.vm.define "Keppel"
  config.vm.provider :lxc do |lxc|
    # Same effect as 'customize ["modifyvm", :id, "--memory", "1024"]' for VirtualBox
    lxc.customize 'cgroup.memory.limit_in_bytes', '3G'
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end


  config.vm.network "forwarded_port", guest: 8080, host: 8082, protocol: "tcp"
  config.vm.network "forwarded_port", guest: 1337, host: 1339, protocol: "tcp"

  #share work directory
  config.vm.synced_folder "~/work/", "/home/vagrant/work"

  config.ssh.forward_agent = true
  config.ssh.forward_x11 = true

end
