---

- name: Download SDK repos
  get_url:
    url: https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
    dest: /tmp/packages-microsoft-prod.deb

- name: Install SDK repos
  apt: deb="/tmp/packages-microsoft-prod.deb"

- name: Update APT cache
  apt: update_cache=yes

- name: Install Dotnet SDK
  apt: pkg=dotnet-sdk-3.1 state=latest
  register:  dotnet-sdk



